INSERT INTO tags (name) VALUES
('Beginner'),
('Intermediate'),
('Advanced'),
('Short Course'),
('Certification'),
('Degree Program'),
('Free'),
('Paid'),
('Self-paced'),
('Instructor-led'),
('Project-based'),
('Exam Prep'),
('Accredited'),
('Live Sessions'),
('Downloadable Resources'),
('High School Students'),
('College Students'),
('Working Professionals'),
('Career Changers'),
('Entrepreneurs'),
('Freelancers'),
('Parents'),
('Seniors'),
('Teachers'),
('Developers'),
('Creatives'),
('Managers'),
('Skill Building'),
('Career Advancement'),
('Hobby Learning'),
('Personal Growth'),
('Job Preparation'),
('Portfolio Development'),
('Test Preparation'),
('Certification Track'),
('Side Hustle'),
('Upskilling'),
('Reskilling'),
('Visual Learning'),
('Hands-on'),
('Reading-heavy'),
('Video Lectures'),
('Interactive'),
('Collaborative'),
('Solo Study'),
('Case Studies'),
('Quizzes & Assessments'),
('Mentorship Included'),
('Python'),
('JavaScript'),
('HTML/CSS'),
('React'),
('SQL'),
('AWS'),
('Excel'),
('Figma'),
('Git'),
('Linux'),
('WordPress'),
('Tableau'),
('Google Analytics'),
('English'),
('Spanish'),
('French'),
('Hindi'),
('Arabic'),
('Subtitled'),
('Multilingual'),
('Localized Content'),
('Region-Specific'),
('Lecture'),
('Tutorial'),
('Workshop'),
('Case Study'),
('Bootcamp'),
('Webinar'),
('Masterclass'),
('MOOC'),
('Capstone Project'),
('Simulation'),
('Reading Material'); 