INSERT INTO categories (name) VALUES
('Mathematics'),
('Physics'),
('Chemistry'),
('Biology'),
('History'),
('Literature'),
('Philosophy'),
('Political Science'),
('Economics'),
('Sociology'),
('Psychology'),
('Business Administration'),
('Entrepreneurship'),
('Marketing'),
('Finance & Accounting'),
('Human Resources'),
('Project Management'),
('Leadership & Strategy'),
('Business Analytics'),
('Computer Science Fundamentals'),
('Software Development'),
('Web Development'),
('Mobile App Development'),
('Data Science & Machine Learning'),
('Artificial Intelligence'),
('Cybersecurity'),
('Cloud Computing'),
('Blockchain'),
('DevOps'),
('Graphic Design'),
('UI/UX Design'),
('Interior Design'),
('Fashion Design'),
('Animation & Motion Graphics'),
('Photography'),
('Video Production'),
('Digital Illustration'),
('English (ESL)'),
('Spanish'),
('French'),
('German'),
('Public Speaking'),
('Writing & Editing'),
('Copywriting'),
('Sign Language'),
('Interpersonal Communication'),
('Productivity & Time Management'),
('Mindfulness & Meditation'),
('Emotional Intelligence'),
('Critical Thinking'),
('Goal Setting & Habits'),
('Life Coaching'),
('Career Development'),
('Resume & Interview Skills'),
('Workplace Communication'),
('Negotiation'),
('Sales & Customer Service'),
('Remote Work Tools & Culture'),
('Excel & Office Tools'),
('Mechanical Engineering'),
('Electrical Engineering'),
('Civil Engineering'),
('Environmental Science'),
('Astronomy'),
('Geology'),
('Biotechnology'),
('Nutrition'),
('Mental Health'),
('Yoga & Meditation'),
('Fitness Training'),
('Public Health'),
('First Aid & CPR'),
('Sports Science'),
('Music Theory'),
('Instrument Training (Piano, Guitar, etc.)'),
('Singing & Vocal Training'),
('Acting & Theatre'),
('Dance (Hip Hop, Ballet, etc.)'),
('Music Production'),
('Cooking & Baking'),
('Gardening'),
('Home Improvement'),
('Travel & Culture'),
('DIY Crafts'),
('Pet Care'),
('Personal Finance'); 